### ISSUE TITLE
Manque les fichiers ExpNot

### ISSUE THREAD

**Issue by cecilebraun** [PolytechUPMC-ICP/polytechupmc-icp-logic-main-3523292#1]
Il manque les fichier ExpNot.cc et ExpNot.hh, impossible de corriger

**Comment by 3523292** [comment]
Bonjour Madame,

Je vous prie de m'excuser. Je pensais les avoir ajouté.
Je viens de le faire.

Respectueusement

2016-11-04 17:36 GMT+01:00 Cecile Braunstein <notifications@github.com>:

**Comment by 3523292** [comment]
Bonjour PolytechUPMC-ICP/polytechupmc-icp-logic-main-3523292,
Paul Edmond FOUMANE vous a laissé un message sur IQ Elite 
Cliquez ici https://a.iqelite.com/j/0FjldA/8fa/ pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : https://a.iqelite.com/common/unsubscribe/?code=d7f8fe35&email=reply@reply.github.com.
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by 3523292** [comment]
Bonjour PolytechUPMC-ICP/polytechupmc-icp-logic-main-3523292,


Paul Edmond FOUMANE vous a laissé un message sur IQ Elite 


Cliquez ici https://a.iqelite.com/j/0FjldA/8fa/ pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : https://a.iqelite.com/common/unsubscribe/?code=d7f8fe35&email=reply@reply.github.com.
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
